#!/bin/bash

ischroot
if [ $? == 0 ]; then exit 0; fi

grep /boot /proc/mounts -q
if [ $? != 0 ]; then echo "/boot is not mounted!"; exit 1; fi

# This prevents vfat symlink errors

FWFILES="LICENCE.broadcom
start_x.elf
fixup_x.dat
bootcode.bin"

for file in $FWFILES
do
	rm -f /boot/$file
done
