#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG

	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade" ] && [ -n "$2" ] && dpkg --compare-versions "$2" lt "1.1.6"; then
		mv /etc/ssh/sshd_config.dpkg-dist /etc/ssh/sshd_config 2>/dev/null
	fi

	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade" ] && systemctl is-enabled sshd.service >/dev/null 2>&1; then systemctl restart sshd.service; fi
	rm -f /var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade
fi
