#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; [ $EXIT -ne 0 ] && exit $EXIT
	fi
}
install_divert ()
{
	if ! dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --add --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; [ $EXIT -ne 0 ] && exit $EXIT
	fi
}

[ -z "$DPKG_MAINTSCRIPT_PACKAGE" ] && exit 1
if [ "$1" = "install" -o "$1" = "upgrade" ]; then

	# remove all diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG

	# install all diverts needed by this version of the package:
	# install_divert PATH_DIV PATH_ORIG

	install_divert /etc/ssh/sshd_config.distributed /etc/ssh/sshd_config
fi
