#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}


if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi

if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG

	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ]; then
		rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"
		systemctl enable bluealsa.service > /dev/null 2>&1
		systemctl enable bluealsa-aplay.service > /dev/null 2>&1
	fi

	systemctl daemon-reload

	if ischroot; then exit 0; fi

	if systemctl is-active bluetooth.target >/dev/null 2>&1; then
		if systemctl is-enabled bluealsa.service; then systemctl restart bluealsa.service; fi >/dev/null 2>&1
		if systemctl is-enabled bluealsa-aplay.service; then systemctl restart bluealsa-aplay.service; fi >/dev/null 2>&1
	fi
	exit 0
fi

