#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; [ $EXIT -ne 0 ] && exit $EXIT
	fi
}

[ -z "$DPKG_MAINTSCRIPT_PACKAGE" ] && exit 1
if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG
fi

systemctl enable connman.service >/dev/null 2>&1

ischroot
if [ $? == 0 ]
then
    systemctl disable bluetooth.service # Don't enable bluetooth by default
    exit 0
fi

systemctl start connman.service
