#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG

	systemctl daemon-reload
	systemctl enable connman.service >/dev/null 2>&1

	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ] || ([ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade" ] && [ -n "$2" ] && dpkg --compare-versions "$2" lt "1.4.4"); then
		systemctl enable http-time.service
	fi
	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade" ] && [ -n "$2" ] && dpkg --compare-versions "$2" lt "1.5.8"; then
		mv /etc/connman.conf.dpkg-dist /etc/connman.conf 2>/dev/null
	fi

	rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_"{install,upgrade}

	if ischroot; then exit 0; fi
	systemctl restart connman.service

	exit 0
fi
