#!/bin/bash

install_divert ()
{
	if ! dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --add --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; [ $EXIT -ne 0 ] && exit $EXIT
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "install" -o "$1" = "upgrade" ]; then

	# install all diverts needed by this version of the package:
	# install_divert PATH_DIV PATH_ORIG

	install_divert /lib/systemd/system/connman.service.distributed /lib/systemd/system/connman.service
fi
