#!/bin/bash

install_divert ()
{
	if ! dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --add --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi

if [ "$1" = "install" ]; then touch "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"; else rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"; fi
if [ "$1" = "upgrade" ]; then touch "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade"; else rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade"; fi

if [ "$1" = "install" -o "$1" = "upgrade" ]; then

	# install all diverts needed by this version of the package:
	# install_divert PATH_DIV PATH_ORIG

	install_divert /lib/systemd/system/connman.service.distributed /lib/systemd/system/connman.service
	install_divert /lib/udev/rules.d/75-persistent-net-generator.rules.distributed /lib/udev/rules.d/75-persistent-net-generator.rules
	rm -f /etc/udev/rules.d/70-persistent-net.rules
fi
