#!/bin/bash

if [ "$1" = "install" -o "$1" = "upgrade" ]; then
        if ! grep /boot /proc/mounts -q; then echo "/boot is not mounted!"; exit 1; fi
        if ! mountpoint /boot; then echo "/boot is not mounted!"; exit 1; fi
        touch /boot/testrw
        if [ $? != 0 ]
        then
            mount -o remount,ro /boot
            fsck /boot
        else
            rm -f /boot/testrw
        fi

	rm -f /boot/SPL /boot/u-boot.img
fi
