#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

dist_upgrade_migrate ()
{
	SRCSFILES=("/etc/apt/sources.list" "/etc/apt/sources.list.d/*osmc*.list")
	# Update APT sources.list
	for SRCSFILE in ${SRCSFILES[@]}; do
		sed 's/buster\/updates/bullseye-security/g;s/buster/bullseye/g' -i $SRCSFILE
	done
	# Signal we want a dist-upgrade and a reboot
	touch /dist_upgrade_wanted /tmp/reboot-needed
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "triggered" ]; then
	echo "Fixing permissions on busybox."
	chmod +s /bin/busybox 2>/dev/null
fi
if [ "$1" = "configure" ]; then
	echo "Fixing permissions on busybox."
	chmod +s /bin/busybox 2>/dev/null

	systemctl daemon-reload
	systemctl enable osmc-prune-devel.timer
	systemctl enable osmc-id-generator.service osmc-report-stats.timer
	systemctl start osmc-id-generator.service osmc-report-stats.timer

	# migrate sources.list only if the previous base-files-osmc version is older than this version
	#if [ -n "$2" ] && dpkg --compare-versions "$2" lt "3.1.8"; then
	#dist_upgrade_migrate
	#fi

	# disable persistent journalling if enabled
	if [ -n "$2" ] && dpkg --compare-versions "$2" lt "3.3.4"; then
		journalctl --relinquish-var
		rm -rf /var/log/journal
	fi

fi
exit 0
