#!/bin/bash
dpkg-divert --remove --package base-files-osmc --rename /etc/issue
dpkg-divert --remove --package base-files-osmc --rename /etc/issue.net
dpkg-divert --remove --package base-files-osmc --rename /etc/os-release
dpkg-divert --remove --package base-files-osmc --rename /usr/share/base-files/motd
