#!/bin/bash
dpkg-divert --add --package base-files-osmc --rename --divert /etc/issue.distributed /etc/issue
dpkg-divert --add --package base-files-osmc --rename --divert /etc/issue.net.distributed /etc/issue.net
dpkg-divert --add --package base-files-osmc --rename --divert /etc/os-release.distributed /etc/os-release
dpkg-divert --add --package base-files-osmc --rename --divert /usr/share/base-files/motd.distributed /usr/share/base-files/motd
