#!/bin/bash

# (c) 2014 Sam Nazarko
# email@samnazarko.co.uk

fb_restore() {
        [ -e /tmp/fb_resolution ] && /bin/fbset $(cat /tmp/fb_resolution)
        /bin/fbset -depth 8 && /bin/fbset -depth 16
        echo 1 >/sys/class/vtconsole/vtcon1/bind
}

export TERM=linux
sudo chown osmc:osmc /sys/class/vtconsole/vtcon*/bind

if [ "$1" == "stop" ]; then
        fb_restore
        exit
fi

if [ ! -e /tmp/fb_resolution ]; then
        /bin/fbset | grep geometry | awk '{print "-xres "$2" -yres "$3" -vxres "$4" -vyres "$5}' | sudo tee /tmp/fb_resolution >/dev/null
fi

EXIT=0
while [ "$EXIT" -ne 1 ]; do
        sudo setcap cap_net_admin,cap_net_bind_service,cap_net_raw=e /usr/lib/kodi/kodi.bin
        LD_PRELOAD="/usr/lib/libarmmem.so" /usr/lib/kodi/kodi.bin --standalone -fs
        CODE="$?"

        fb_restore
        sudo chmod a+rw /dev/tty1
        /usr/bin/setterm -cursor off >/dev/tty1
        /usr/bin/clear >/dev/tty1
        /usr/bin/ply-image "$CODE"

        if [ "$CODE" -eq 0 ]; then
                read -n 1 -s -t 10 key </dev/tty1
                if [ "$key" = $'\e' ]; then
                        /bin/fbset -depth 8 && /bin/fbset -depth 16
                        /usr/bin/setterm -cursor on >/dev/tty1
                        sudo setsid /sbin/agetty -t 30 115200 tty1 linux
                fi
        fi
done
