#!/bin/bash

# (c) 2014 Sam Nazarko
# email@samnazarko.co.uk

#TODo: Add check with 'read' to make sure we can exit

sudo chown -R osmc:osmc /sys/class/vtconsole/vtcon*

EXIT=0

while [ "$EXIT" -ne 1 ]
do
echo 0 > /sys/class/vtconsole/vtcon1/bind
sudo setcap cap_net_admin,cap_net_bind_service,cap_net_raw=e /usr/lib/kodi/kodi.bin
LD_PRELOAD="/usr/lib/libarmmem.so" /usr/lib/kodi/kodi.bin --standalone -fs
CODE="$?"
echo 1 > /sys/class/vtconsole/vtcon1/bind
fbset -depth 8 && fbset -depth 16
/usr/bin/ply-image "$CODE"
done
