#!/bin/bash

# (c) 2014-2015 Sam Nazarko
# email@samnazarko.co.uk

fb_restore() {
	echo 1 >/sys/class/vtconsole/vtcon1/bind
	/bin/fbset -depth 32 && /bin/fbset -depth 16
}

export TERM=linux
chown osmc:osmc /sys/class/vtconsole/vtcon*/bind

if [ "$1" = "stop" ]; then
	fb_restore
	exit
fi

trap 'wait; exit 0' SIGTERM

chmod a+rw /dev/tty1
/usr/bin/setterm --blank 0 </dev/tty1 >/dev/tty1

while true; do
	umount /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq >/dev/null 2>&1
	mount --bind /sys/devices/system/cpu/cpu0/cpufreq/scaling_max_freq /sys/devices/system/cpu/cpu0/cpufreq/scaling_cur_freq
	/bin/fbset -depth 16 && /bin/fbset -depth 32

	if [ -f /home/osmc/.kodi.bin ]; then KODI=/home/osmc/.kodi.bin; else KODI=/usr/lib/kodi/kodi.bin; fi
	setcap 'cap_net_bind_service=+ep' $KODI
	echo 0 > /sys/class/vtconsole/vtcon1/bind
	sudo -u osmc $KODI --standalone -fs --lircdev /var/run/lirc/lircd
	CODE="$?"

	fb_restore
	chmod a+rw /dev/tty1
	systemctl status getty@tty1 >/dev/null; GETTY=$?
	if [ "$GETTY" -ne 0 ]; then
		chvt 1
		/usr/bin/setterm --cursor off >/dev/tty1
		/usr/bin/clear >/dev/tty1
		/usr/bin/ply-image "$CODE"
		read -n 1 -s -t 10 key </dev/tty1
	fi
	if [ "$key" = $'\e' -o "$GETTY" -eq 0 ]; then
		/bin/fbset -depth 32 && /bin/fbset -depth 16
		/usr/bin/setterm --cursor on >/dev/tty1
		systemctl start getty@tty1
		count=30
		while [ $count -gt 0 ]; do
			who | awk '{print $2}' | grep -q tty1
			if [ "$?" -eq 0 ]; then
				count=5
			else
				let count=count-5
			fi
			sleep 5
		done
		systemctl stop getty@tty1
	fi
done
