#!/bin/bash

if ischroot; then OWNER="1000:1000"; else OWNER="osmc:osmc"; fi
chown -R $OWNER /usr/share/kodi/addons/skin.osmc
chown -R $OWNER /usr/share/kodi/addons/script.module.simplejson
chown -R $OWNER /usr/share/kodi/script.module.unidecode
chown -R $OWNER /usr/share/kodi/script.skinshortcuts
chown -R $OwNER /usr/share/kodi/service.skin.widgets
