#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG

	systemctl daemon-reload

	# work around for: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762080
	mkdir -p /var/log/samba

	usermod -a -G sambashare osmc

	# only do this for upgrade not install
	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade" ]
	then
		rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_upgrade"
		if [ -n "$2" ] && dpkg --compare-versions "$2" lt "1.1.1" && [ ! -e /etc/samba/smb-shares.conf ]; then

			cat <<- 'EOF' > /etc/samba/smb-shares.conf
			# Deprecated devices share. If you do not need this you can remove it.
			[devices]
			    browsable = yes
			    read only = no
			    valid users = osmc
			    path = /media
			    force user = root
			    comment = Deprecated (Please use the Auto-mount Volume shares)
			    hide files = /$RECYCLE.BIN/System Volume Information/desktop.ini/thumbs.db/
			EOF
		fi
	fi

	# only do this for install not upgrade
	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ]
	then
		rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"
		(echo osmc; echo osmc) | smbpasswd -a osmc
		systemctl disable smbd.service nmbd.service samba-ad-dc.service
		systemctl stop smbd.service nmbd.service samba-ad-dc.service
		systemctl enable samba.service
	fi
	if systemctl is-enabled samba.service >/dev/null; then systemctl start samba.service; fi
fi
