#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG

	# work around for: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=762080
	mkdir -p /var/log/samba

	# only do this for install not upgrade
	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ]
	then
		rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"
		(echo osmc; echo osmc) | smbpasswd -a osmc
		systemctl disable smbd.service nmbd.service
		systemctl stop smbd.service nmbd.service
		systemctl enable samba.service
	fi
	if systemctl is-enabled samba.service >/dev/null; then systemctl start samba.service; fi
fi
