#!/usr/bin/env python
# -*- coding: utf-8 -*-

warranty = """Limited warranty

Sam Nazarko Trading Ltd warrants the original purchaser only that the Product will be free from defects in material and workmanship under normal use for a period of twelve months after the date of original shipment from Sam Nazarko Trading Ltd. Warranty shall not apply: 1) to any Product subject to accident, misuse, neglect, alteration, acts of God, improper transport, improper storage, improper use or application, improper installation, improper testing or unauthorised repair; or 2) to cosmetic problems or defects that result from normal wear and tear under ordinary use and do not affect the performance or use of the product 3) if the "rubber pads" have been interfered with indicating unauthorised opening of the unit. Sam Nazarko Trading Ltd warranty applies only to a product that is manufactured by or for Sam Nazarko Trading Ltd. If the products develops a covered defect within the warranty period, Sam Nazarko Trading Ltd, will at its option, either repair or replace the Product without charge, provided that the product is returned within the warranty period. The buyer is responsible for all freight charges relating to the return of the unit for repair or replacement.

THE FOREGOING ARE YOUR EXCLUSIVE WARRANTIES RELATING TO THE PRODUCT AND SAM NAZARKO TRADING LTD, HEREBY DISCLAIMS ALL IMPLIED WARRANTIES, INCLUDING THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE.

Because it is impossible for Sam Nazarko Trading Ltd to know the purpose for which you acquired this Product or the uses to which you will put this Product, you must assume full responsibility for the selection of the Product for its installation and use. While every reasonable effort has been made to ensure that you will receive a product you can use and enjoy, Sam Nazarko Trading Ltd does not warrant that the functions of the Product will meet your requirements or that the operation of the Product will be uninterrupted or error-free. Sam Nazarko Trading Ltd is not responsible for problems caused by the interaction of the Product with any software or hardware.

THIS WARRANTY IS VOID IF THE PRODUCT IS OPENED ALTERED OR DAMAGED. To obtain warranty service or technical support please contact: sales@osmc.tv and/or request a return authorisation number.

THESE ARE YOUR SOLE AND EXCLUSIVE REMEDIES FOR ANY AND ALL CLAIMS THAT YOU MAY HAVE ARISING OUT OF OR IN CONNECTION WITH THIS PRODUCT, WHERE MADE OR SUFFERED BY YOUR OR ANOTHER PERSON AND WHETHER BASED IN CONTRACT OR TORT. IN NO EVENT WILL SAM NAZARKO TRADING LTD BE LIABLE TO YOU OR ANY OTHER PARTY FOR ANY DIRECT, INDIRECT, GENERAL, SPECIAL INCIDENTAL, CONSEQUENTIAL, EXEMPLARY OR OTHER DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE PRODUCT (INCLUDING WITHOUT LIMITATION, DAMAGES FOR LOSS OF BUSINESS PROFITS, BUSINESS INTERPRETATIONS, LOSS OF INFORMATION OR ANY OTHER PECUNIARY LOSS) OR FROM BREACH OF WARRANTY, EVEN IF SAM NAZARKO TRADING LTD HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES, IN NO CASE, SHALL SAM NAZARKO TRADING LTD LIABILITY EXCEED THE AMOUNT YOU PAID FOR THE PRODUCT

Disclaimers

The information furnised by Sam Nazarko Trading Ltd in all communications, including but not limited to its website, its wiki pages and informations its employees post on the OSMC forum or send via email, send via mail or communicate verbally is believed to be accurate and reliable. However no responsibility is assuming by Sam Nazarko Trading Ltd for its use and shall in no event be liable for any loss of profit or any other commercial damage, including, but not limited to special, incidental, consequential, or other damages. Sam Nazarko Trading Ltd reserves the right to change circuitry, software, documentation and specifications at any time without notification to the customer

Sam Nazarko Trading Ltd products are not intended for use in life support, critical care, medical, safety equipment or similar applications where product failure could result in loss of life or personal or physical harm, or any military or defense application, or any governmental procurement to which special terms of provisions may apply."""