#!/bin/bash

if [ "$1" = "remove" ]; then
	systemctl stop videofirmware.service >/dev/null 2>&1
	systemctl stop apploader.service >/dev/null 2>&1
	systemctl disable videofirmware.service >/dev/null 2>&1
        exit 0
fi

