#!/bin/bash

if [ "$1" = "configure" ]; then

	systemctl daemon-reload
	systemctl enable brcm43xx-firmware.service brcm43xx.service >/dev/null 2>&1
	if ischroot; then exit 0; fi
	touch /tmp/reboot-needed
fi
