#!/bin/busybox sh

export OPTION_DO_FSCK="1"
export OPTION_FORCE_FSCK="0"
export OPTION_ROOT="/dev/vero-nand/root"
export OPTION_ROOTDELAY="0"
export OPTION_FILESYSTEM="ext4"
export OPTION_INIT="/sbin/splash_early"
export OPTION_MOUNT_OPTIONS=""
export OPTION_MOUNT_PATH="/real_root"

hdmimode=720p
for arg in $(/bin/busybox cat /proc/cmdline); do
  case $arg in
   hdmimode=*)
     hdmimode="${arg#*=}"
   ;;
esac
done

# Enable framebuffer device
echo "$hdmimode" > /sys/class/display/mode
echo 0 > /sys/class/graphics/fb0/blank

# Disable framebuffer scaling
echo 0 > /sys/class/graphics/fb0/free_scale
echo 0 > /sys/class/graphics/fb1/free_scale

# Configure framebuffer with double buffer
case "$hdmimode" in
  720*)
   /bin/busybox fbset -fb /dev/fb0 -g 1280 720 1920 2160 32
  ;;
  1080*)
   /bin/busybox fbset -fb /dev/fb0 -g 1920 1080 1920 2160 32
  ;;
esac

# Include deinterlacer into default VFM map
echo rm default > /sys/class/vfm/map
echo add default decoder ppmgr deinterlace amvideo > /sys/class/vfm/map

# Better entropy
for part in /sys/block/*/queue/add_random; do
echo 0 > "$part"
done

# Set up NAND
# ToDo: only if bootfromsd
/usr/sbin/lvchange -aly /dev/vero-nand/root --ignorelockingfailure >/dev/null 2>&1
