all:
	sudo bash build.sh

clean:
	sudo rm -f *.deb >/dev/null 2>&1
	sudo rm -rf files/opt/vc > /dev/null 2>&1
	sudo rm -rf files-dev/opt/vc > /dev/null 2>&1
	sudo rm -rf files-src/opt/vc > /dev/null 2>&1
	sudo rm -rf src > /dev/null 2>&1
