#!/bin/sh

processimage()
{
    echo "Processing kernel image"
    # use mkknlimg to rename the kernel too
    LANG=C /usr/bin/mkknlimg --dtok ${1} /boot/kernel.img >/dev/null 2>&1
    EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
}

if [ -f /boot/bootcode.bin ]; then processimage $2; fi
