#!/bin/sh

# (c) 2015 Sam Nazarko
# email@samnazarko.co.uk

/bin/mount -t proc proc /proc
/bin/mount -o remount,rw,noatime /
/bin/mount -t sysfs sysfs /sys
/bin/mount -t devtmpfs dev /dev

exec 0</dev/console
exec 1>/dev/console
exec 2>/dev/console

boot_kernel()
{
	# Mounts the disk, looks for a kernel and boots
	/bin/mount /dev/${1} /mnt
	if [ -f /mnt/kernel.img ]
	then
		echo -e "Found a kernel.img"
		if [ -f /mnt/cmdline.txt ]
		then
			echo "Found a cmdline.txt"
			boot_cmd=$(cat /mnt/cmdline.txt)
		fi
		if [ ! -z $boot_cmd ]; then /bin/kexec --load /mnt/kernel.img --command-line=$boot_cmd; else /bin/kexec --load /mnt/kernel.img; fi
		/bin/kexec -e
	else
	/bin/umount /mnt
	fi
}

echo -e "Trying to mount internal disk"
boot_kernel "sda" # Try internal disk first
echo -e "Trying to mount USB"
boot_kernel "sdb" # Try USB afterwards
