#!/bin/bash


ischroot
if [ $? == 0 ]
then
    if ! grep -q osmcdev=rbp /boot/cmdline.txt
    then
        rm -rf /usr/share/kodi/addons/script.module.osmcsetting.pi* >/dev/null 2>&1
    fi
else
    if ! grep -q osmcdev=rbp /proc/cmdline
    then
        rm -rf /usr/share/kodi/addons/script.module.osmc.setting.pi* >/dev/null 2>&1
    fi
fi

for dir in /usr/share/kodi/addons/service.osmc.settings/ /usr/share/kodi/addons/script.module.osmcsetting.*/
do
    if pushd $dir >/dev/null 2>&1; then pycompile . >/dev/null 2>&1; popd >/dev/null 2>&1; fi
done
