#!/bin/bash

function is_rbp()
{
	if ischroot
	then
		dpkg -l | grep -q "rbp-bootloader-osmc"
		return
	else
		grep -q osmcdev=rbp /proc/cmdline > /dev/null 2>&1
		return
	fi
}

function is_vero()
{
        if ischroot
        then
                dpkg -l | grep -q "vero-userland-osmc"
                return
        else
                grep -q osmcdev=vero /proc/cmdline > /dev/null 2>&1
                return
        fi
}

if [ "$1" = "configure" ]
then
	if ! is_rbp; then rm -rf /usr/share/kodi/addons/script.module.osmcsetting.pi* >/dev/null 2>&1; fi
	if ischroot; then OWNER="1000:1000"; else OWNER="osmc:osmc"; fi
	chown -R $OWNER /usr/share/kodi/addons/script.module.elementtree
	chown -R $OWNER /usr/share/kodi/addons/script.module.xmltodict
	chown -R $OWNER /usr/share/kodi/addons/script.module.osmcsetting.*
	chown -R $OWNER /usr/share/kodi/addons/service.osmc.settings
fi
