#!/bin/sh
if /usr/bin/ischroot; then exit 0; fi
/bin/mountpoint /boot > /dev/null 2>&1
if [ $? != 0 ]
then
    echo "/boot is not mounted!"
    exit 1
fi
boot=$(grep "/boot" /etc/fstab | awk {'print $1'})
/bin/umount /boot
/sbin/fsck.hfsplus $boot
/bin/mount -t hfsplus -o rw,force /boot
exit 0
