#!/bin/sh

processimage()
{
    LANG=C /bin/dd if=${1} of=/dev/boot bs=1M conv=fsync
    STATUS=$?
    if [ "$STATUS" != 0 ]
    then
        echo "Could not upload kernel to NAND" >&2
        exit $STATUS
    fi
    # Make it easy to see the active version and give target installer a handle
    cp ${2} /boot/kernel.img >/dev/null 2>&1
}

processimage $2
