#!/bin/sh
################################################################################
# wakeup_enable
################################################################################

devpath=`readlink -f "/sys/${DEVPATH}"`
while echo "${devpath}" | /bin/grep -q '^/sys/devices/' > /dev/null 2>&1 ; do
    if test -e "${devpath}/power/wakeup" ; then
        state=`cat "${devpath}/power/wakeup"`
        if test "x${state}" = "xdisabled" ; then
            echo "enabled" > "${devpath}/power/wakeup"
        fi
    fi
    devpath=`dirname "${devpath}"`
done

exit 0
