#!/bin/bash

remove_divert ()
{
	if dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --remove --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; [ $EXIT -ne 0 ] && exit $EXIT
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
#if [ "$1" = "configure" ]; then

	# remove only diverts that prior versions of this package added which are no longer needed:
	# remove_divert PATH_DIV PATH_ORIG
#fi

systemctl enable udisks-glue.service >/dev/null 2>&1

ischroot
if [ $? == 0 ]; then exit 0; fi

systemctl start udisks-glue.service
