#!/bin/bash
PATH_ORIG="/etc/kernel-img.conf"
PATH_DIV="/etc/kernel-img.conf.distributed"
PACKAGE="rbp-userland-osmc"

dpkg-divert --listpackage "$PATH_ORIG" | grep -q "$PACKAGE"
if [ $? -eq 0 ] && [ "$1" = "remove" ]; then
	dpkg-divert --remove --package "$PACKAGE" --rename --divert "$PATH_DIV" "$PATH_ORIG"
fi
