#!/bin/busybox sh

# (c) 2014-2015 Sam Nazarko
# email@samnazarko.co.uk

# Abstract settings and defaults

print_message()
{
	# Prints a message that won't be trimmed by overscan and will be visible
	echo -e "\n\n\n\n\nOSMC initrd\n\n${1}"
}

install_busybox_symlinks()
{
        # Installs BusyBox symlinks to make the shell actually usable
	/bin/busybox --install -s
}

OPTION_DO_FSCK="1"
OPTION_ROOT="/dev/mmcblk0p2"
OPTION_ROOTDELAY="0"
OPTION_FILESYSTEM="ext4"
OPTION_INIT="/sbin/splash_early"
# Each concatenated mount option should have a leading comma.
OPTION_MOUNT_OPTIONS=""
OPTION_MOUNT_PATH="/real_root"
OPTION_NFS_IP_TYPE="dhcp"

# Set up our mounts

/bin/busybox mount -t devtmpfs devtmpfs /dev
/bin/busybox mount -t proc proc /proc
/bin/busybox mount -t sysfs sysfs /sys
/bin/busybox mount -t tmpfs tmpfs /run

# Load platform specific stuff
. init-device

# A nicer console

echo 0 > /sys/devices/virtual/graphics/fbcon/cursor_blink
echo 0 > /proc/sys/kernel/printk
/bin/busybox clear

# Set up device nodes

echo /bin/busybox mdev > /proc/sys/kernel/hotplug
/bin/busybox mdev -s

# Read /proc/cmdline and find out what we're doing.

for option in $(/bin/busybox cat /proc/cmdline); do
	case $option in
	  rootdelay=*)
	    OPTION_ROOTDELAY="${option#*=}"
	    ;;
	  root=*)
		OPTION_ROOT="${option#*=}"
		;;
	  rootfstype=*)
		OPTION_FILESYSTEM="${option#*=}"
		;;
	  init=*)
		OPTION_INIT="${option#*=}"
		;;
	  nfsroot=*)
		OPTION_DO_FSCK="0"
		OPTION_FILESYSTEM="nfs"
		OPTION_ROOT="${option#*=}"
		OPTION_MOUNT_OPTIONS="$(echo $OPTION_ROOT | /bin/busybox cut -f 2 -d ,)"
		OPTION_ROOT="$(echo $OPTION_ROOT | /bin/busybox cut -f 1 -d ,)"
		OPTION_FILESYSTEM="nfs"
		;;
	  ip=*)
		OPTION_NFS_IP_TYPE="${option#*=}"
		;;
	  nofsck)
		OPTION_DO_FSCK="0"
		;;
	  osmcrescue)
		install_busybox_symlinks
		/bin/busybox sh
		;;
	 esac
done

# Should we check the filesystem?

if [ "$OPTION_DO_FSCK" -eq 1 ]
then
	# Verify filesystem integrity
	FSCK_BIN="/bin/e2fsck"
	if [ -f /bin/fsck.${OPTION_FILESYSTEM} ]; then FSCK_BIN="/bin/fsck.${OPTION_FILESYSTEM}"; fi
	echo -e "\n\n\n\n"
	$FSCK_BIN -p -C 0 "$OPTION_ROOT"
	fsck_result="$?"
	if [ "$(( $fsck_result & 2 ))" = 2 ]
	then
		print_message "OSMC has repaired some filesystem corruption on your system and needs to reboot"
		/bin/busybox sleep 10
		/bin/busybox reboot
	fi
		if [ "$(( $fsck_result & 4 ))" = 4 ]
	then
		print_message "OSMC is significantly corrupted. We will our best to repair this system"
		/bin/busybox sleep 5
		$FSCK_BIN -f -y -C 0 "$OPTION_ROOT"
		fsck_result="$?"
		if [ "$(( $fsck_result & 8 ))" = 8 ]
		then
			# We are broken for good
			print_message "OSMC cannot repair the filesystem. Please re-install OSMC from osmc.tv/download"
			while true
			do
				/bin/busybox sleep 1
			done
		fi
		print_message "OSMC has repaired your filesystem"
		/bin/busybox sleep 10
	fi
fi

/bin/busybox mkdir -p "$OPTION_MOUNT_PATH"

# Deactivate the hotplugger. systemd will take over
echo "" > /proc/sys/kernel/hotplug

# Let's try and mount

if [ "$OPTION_ROOTDELAY" -gt 0 ]
then
	COUNTER=0
	while [ "$COUNTER" -lt "$OPTION_ROOTDELAY" ]
	do
		/bin/busybox sleep 1
		COUNTER=$((COUNTER+1))
	done
fi

if [ "$OPTION_FILESYSTEM" == "nfs" ]
then
	# Bring up the network
	/bin/busybox mkdir -p /var/run/ifstate
	if echo $OPTION_NFS_IP_TYPE | /bin/busybox grep -q "dhcp"
	then
		/bin/busybox mkdir -p /etc/network
		/bin/busybox mkdir -p /etc/network/if-up.d
		echo "auto eth0
		iface eth0 inet dhcp" > /etc/network/interfaces
		/bin/busybox ifup eth0
		/bin/busybox udhcpc -i eth0
		/bin/busybox ifconfig
		/bin/busybox sleep 10
	else
		NFS_IP_ADDR=$(echo $OPTION_NFS_IP_TYPE | /bin/busybox cut -d : -f 1)
                NFS_IP_GW=$(echo $OPTION_NFS_IP_TYPE | /bin/busybox cut -d : -f 3)
                NFS_IP_MASK=$(echo $OPTION_NFS_IP_TYPE | /bin/busybox cut -d : -f 4)
                /bin/busybox ifconfig eth0 "$NFS_IP_ADDR" netmask "$NFS_IP_MASK"
                /bin/busybox route add default gw "$NFS_IP_GW" eth0
        fi
else
	OPTION_MOUNT_OPTIONS="ro${OPTION_MOUNT_OPTIONS}"
fi

if [ "$OPTION_MOUNT_OPTIONS" ]; then OPTION_MOUNT_OPTIONS="-o $OPTION_MOUNT_OPTIONS"; fi
/bin/busybox mount -t "$OPTION_FILESYSTEM" "$OPTION_ROOT" "$OPTION_MOUNT_PATH" $OPTION_MOUNT_OPTIONS
mount_result="$?"
if [ "$mount_result" -eq 0 ]
then
	# If we checked the filesystem, tell systemd
	if [ "$OPTION_DO_FSCK" -eq 1 ]
	then
		/bin/busybox mkdir -p /run/initramfs
		/bin/busybox touch /run/initramfs/fsck-root
		/bin/busybox cat /fsck.log >/dev/kmsg 2>/dev/null
	fi
	# Let's move our mounts over
	/bin/busybox mount --move /dev "$OPTION_MOUNT_PATH"/dev
	/bin/busybox mount --move /proc "$OPTION_MOUNT_PATH"/proc
	/bin/busybox mount --move /sys "$OPTION_MOUNT_PATH"/sys
	/bin/busybox mount --move /run "$OPTION_MOUNT_PATH"/run
	exec /bin/busybox switch_root "$OPTION_MOUNT_PATH" "$OPTION_INIT" $*
else
	print_message "OSMC cannot mount $OPTION_ROOT of $OPTION_FILESYSTEM filesystem"
	# Drop to a shell
	install_busybox_symlinks
	/bin/busybox sh
fi
