#!/bin/bash

if [ "$SLAVENAME" = "SlaveName" ] || [ -z "$SERVER" ] || [ -z "$SLAVENAME" ] || [ -z "$SECRET" ]; then
	echo "Exiting because /etc/jenkins-slave.conf has not been configured."
	exit
fi

HOSTNAME=$(echo "$SERVER" | sed 's/:.*//')

while true; do
	# Work around jenkins slave.jar dns lookup bug
	while true; do if host $HOSTNAME; then break; else sleep 5; fi; done

	cd /opt/osmc-tc/jenkins-slave/
        PROTO="http"
        echo ^d | openssl s_client -connect $SERVER:${2:-443} && PROTO="https"

        curl -O -L ${PROTO}://$SERVER:${2:-443}/jnlpJars/slave.jar
	java -jar slave.jar -jnlpUrl "https://$SERVER/computer/$SLAVENAME/slave-agent.jnlp" -secret "$SECRET"
	echo "Java exited with return code $? - relaunching in 60 seconds."
	sleep 60
done
