#!/bin/bash
export LD_LIBRARY_PATH=/usr/lib/osmc
echo $(pwd)
if [[ $EUID -eq 0 ]]; then
    ./qt_host_installer
elif command -v gksudo; then
    gksudo ./qt_host_installer
elif command -v kdesu; then
    kdesu ./qt_host_installer
elif command -v xdg-su; then
    kdesu ./qt_host_installer
else 
    sudo -i ./qt_host_installer
fi
