all:
	@echo "Specify a target:\nmake rbp1\nmake rbp2"

rbp1:
	sudo bash build.sh rbp1

rbp2:
	sudo bash build.sh rbp2

clean:
	sudo rm -rf output > /dev/null 2>&1
	sudo rm -f boot*.tar.xz > /dev/null 2>&1
	sudo rm -f root*.tar.xz > /dev/null 2>&1
