all:
	@echo "Specify a target:\nmake vero3\nmake vero5\n"

vero3:
	sudo bash build.sh "vero3"

vero5:
	sudo bash build.sh "vero5"

clean:
	sudo rm -f *.deb > /dev/null 2>&1
	sudo rm -rf files/usr > /dev/null 2>&1
