#!/bin/bash

if [ "$1" = "configure" ]; then

	systemctl daemon-reload
	if [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ]; then
		rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"
		systemctl enable aml-vnc.service >/dev/null 2>&1
	fi

	if ischroot; then exit 0; fi
	if systemctl is-enabled aml-vnc.service >/dev/null; then systemctl start aml-vnc.service; fi
fi
