#!/bin/bash

umount /opt/osmc-tc/appletv-toolchain-osmc/proc >/dev/null 2>&1
umount /opt/osmc-tv/appletv-toolchain-osmc/mnt >/dev/null 2>&1
rm -rf /opt/osmc-tc/appletv-toolchain-osmc/* >/dev/null 2>&1
