all:
	@echo "Usage: make vero2\n"

vero2:
	sudo bash build.sh vero2

clean:
	sudo rm -f *.deb >/dev/null 2>&1
	sudo rm -rf files/usr/osmc/lib > /dev/null 2>&1
	sudo rm -rf files-dev/usr/osmc/include>/dev/null 2>&1
