#!/bin/sh

processimage()
{
    if ischroot; then exit 0; fi
    LANG=C /bin/dd if=/boot/kernel-${1}.img of=/dev/boot bs=1M conv=fsync
    STATUS=$?
    if [ "$STATUS" != 0 ]
    then
        echo "Could not upload kernel to eMMC" >&2
        exit $STATUS
    fi
}

processdtb()
{
    if ischroot; then exit 0; fi
    # Need permission to do an upload
    /usr/bin/fw_setenv upgrade_step 2
    LANG=C /bin/dd if=/boot/dtb-${1}.img of=/dev/dtb bs=256k
    STATUS=$?
    if [ "$STATUS" != 0 ]
    then
        echo "Could not upload DTB to eMMC" >&2
        exit $STATUS
    fi
}

processimage $1
processdtb $1
