#!/bin/bash

verify_sane()
{
    dt=$(tr -d '\0' </proc/device-tree/model)
    if [ "$dt" != "Vero4K" ] && [ "$dt" != "Vero4KPlus" ]; then echo "Unsupported device" && exit 1; fi
    if [ "$dt" == "Vero4K" ]; then if grep -q revision=4kplus /proc/cmdline; then echo "Bootloader and device mismatch" && exit 1; fi; fi
    if [ "$dt" == "Vero4KPlus" ]; then if ! grep -q revision=4kplus /proc/cmdline; then echo "Bootloader and device mismatch" && exit 1; fi; fi
}

do_jump()
{
    if grep -q revision=4kplus /proc/cmdline; then echo "Injecting jump for V4K+" && /usr/bin/fw_setenv storeboot 'if imgread kernel boot ${loadaddr}; then mw 0x1000000 0; bootm ${loadaddr}; fi; run update;' || exit 1; fi
}
processimage()
{
    if ischroot; then exit 0; fi
    LANG=C /bin/dd if=/boot/kernel-${1}.img of=/dev/boot bs=1M conv=fsync
    STATUS=$?
    if [ "$STATUS" != 0 ]
    then
        echo "Could not upload kernel to eMMC" >&2
        exit $STATUS
    fi
    rm -rf /lib/modules/${1}_kernel_*
}

verify_sane
do_jump
processimage $1
