#!/bin/bash


if [ "$1" = "configure" ] && [ -e "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install" ]; then
	rm -f "/var/run/${DPKG_MAINTSCRIPT_PACKAGE}_install"
	if ischroot; then exit 0; fi
	sed '/^\/usr\/lib\/libarmmem.so$/d' -i /etc/ld.so.preload
	echo "/usr/lib/libarmmem.so" > /etc/ld.so.preload
fi
