#!/bin/bash

if [ "$1" = "install" -o "$1" = "upgrade" ]; then
	umount /opt/osmc-tc/armv6l-toolchain-osmc/proc >/dev/null 2>&1
	chroot /opt/osmc-tc/armv6l-toolchain-osmc umount /proc >/dev/null 2>&1
	umount /opt/osmc-tc/armv6l-toolchain-osmc/mnt >/dev/null 2>&1
	if [ -n "$(ls -A /opt/osmc-tc/armv6l-toolchain-osmc/mnt 2>/dev/null)" ]; then exit 1; fi
	rm -rf /opt/osmc-tc/armv6l-toolchain-osmc/ >/dev/null 2>&1
fi
