#!/bin/bash

if [ "$1" = "remove" ]; then
	umount /opt/osmc-tc/i386-toolchain-osmc/proc >/dev/null 2>&1
	chroot /opt/osmc-tc/i386-toolchain-osmc umount /proc >/dev/null 2>&1
	umount /opt/osmc-tc/i386-toolchain-osmc/mnt >/dev/null 2>&1
	if [ -n "$(ls -A /opt/osmc-tc/i386-toolchain-osmc/mnt 2>/dev/null)" ]; then exit 1; fi
fi
