#!/bin/bash

install_divert ()
{
	if ! dpkg-divert --listpackage "$2" | grep -q "$DPKG_MAINTSCRIPT_PACKAGE"; then
		dpkg-divert --add --package "$DPKG_MAINTSCRIPT_PACKAGE" --rename --divert "$1" "$2"
		EXIT=$?; if [ $EXIT -ne 0 ]; then exit $EXIT; fi
	fi
}

if [ -z "$DPKG_MAINTSCRIPT_PACKAGE" ]; then exit 1; fi
if [ "$1" = "install" -o "$1" = "upgrade" ]; then

	# install all diverts needed by this version of the package:
	# install_divert PATH_DIV PATH_ORIG
	install_divert /usr/share/alsa/cards/vc4-hdmi.conf.distributed /usr/share/alsa/cards/vc4-hdmi.conf
        if ischroot; then exit 0; fi
        if ! mountpoint /boot >/dev/null 2>&1; then echo "/boot is not mounted!"; exit 1; fi
        touch /boot/testrw
        if [ $? != 0 ]
        then
            mount -o remount,ro /boot
            fsck /boot
        else
            rm -f /boot/testrw
        fi
        # This prevents vfat symlink errors
        rm -f /boot/config.txt
	systemctl stop brcm43xx.service >/dev/null 2>&1
	exit 0
fi
