#!/bin/bash

if [ "$1" = "remove" ]; then
	systemctl disable pulseaudio.service > /dev/null 2>&1
	systemctl stop pulseaudio.service > /dev/null 2>&1
	sudo -u osmc systemctl --user enable pulseaudio.service > /dev/null 2>&1
	exit 0
fi
