all:
	sudo bash build.sh

clean:
	sudo rm -f *.deb > /dev/null 2>&1
	sudo rm -f *.fw* > /dev/null 2>&1
	sudo rm -f *.zip > /dev/null 2>&1
	sudo rm -f *.exe > /dev/null 2>&1
	sudo rm -f *.ashx* > /dev/null 2>&1
	sudo rm -f *.mc > /dev/null 2>&1
	sudo rm -f get_dvb_firmware > /dev/null 2>&1
	sudo rm -rf files/lib/firmware > /dev/null 2>&1
